# gitlab CI/CD pipeline配置文件

stages:
  - lint

# 准备工作
before_script:
  - ls

# lint stage
# job 1 : golangci-lint
golangci-lint:
  image: golangci/golangci-lint:v1.45.2
  stage: lint
  script:
    - golangci-lint run -v

