[server]
address = ":8080"
router_prefix = "v1beta1"
prometheus_addr = ":9090"
log_format = "text"
log_level = "debug"
app_env = "stage"
signature_auth = false
default_key_password = "NFT-Avata-Services-ApiV1"

[mysql]
db_name = "nftp_open_api"
host = "192.168.150.40"
port = "23306"
user = "nftp"
password = "nftppassword"
max_idle_conns = 10
max_life_time = "1h"
max_open_conns = 100

[chain]
chain_id = "dev"
grpc_address = "192.168.150.42:9090"
rpc_address = "tcp://192.168.150.42:26657"
project_id = "a36dc219dbdd4dbe809766accbed0ac6"
project_key = ""
chain_account_addr = ""
chain_encryption = "secp256k1"
ddc_encryption = "eth_secp256k1"

gas_coefficient = 1.5
gas = 400000
amount = 200000
account_gas = 4000000
denom = "uirita"


[redis]
address = "127.0.0.1:6379"
db = 0
password = ""

[ddc]
ddc_authority_address = "0x0754D6B28cB82cce0E19FE495e9eca445F1431aF"
ddc_charge_address = "0x49cB5903bA052d6898e784d3DebB1E01b6361e70"
ddc_721_address = "0xAA06A5BC9D41992AAa4229198cac06fC56C8556f"
ddc_1155_address = "0xb7333032F3e8858Cab5e1BC5075A726A4E62e0b4"
ddc_gateway_url = "http://192.168.150.42:8545"