[server]
address = ":8080"
router_prefix = "v1beta1"
prometheus_addr = ":9090"
log_format = "text"
log_level = "debug"
app_env = "stage"
signature_auth = false

[mysql]
db_name = "nftp_open_api"
host = "192.168.150.40"
port = "23306"
user = "nftp"
password = "nftppassword"
max_idle_conns = 10
max_life_time = "1h"
max_open_conns = 100

[chain]
chain_id = "dev"
grpc_address = "192.168.150.42:9090"
rpc_address = "tcp://192.168.150.42:26657"
project_id = "a36dc219dbdd4dbe809766accbed0ac6"
project_key = ""
chain_account_addr = ""
chain_encryption = "secp256k1"


gas_coefficient = 1.5
gas = 400000
amount = 200000
account_gas = 4000000
denom = "uirita"


[redis]
address = "127.0.0.1:6379"
db = 0
password = ""