[server]
address = ":8080"
router_prefix = "v1beta1"
prometheus_addr = ":9090"
log_format = "text"
log_level = "debug"
app_env = "dev"
signature_auth = false
default_key_password = "NFT-Avata-Services-ApiV1"
account_white_list = ""
account_count = ""

[mysql]
db_name = "nftp_open_api"
host = "192.168.150.40"
port = "23306"
user = "nftp"
password = "nftppassword"
max_idle_conns = 10
max_life_time = "1h"
max_open_conns = 100

[chain]
chain_id = "dev"
grpc_address = "192.168.150.42:9090"
rpc_address = "tcp://192.168.150.42:26657"
project_id = "a36dc219dbdd4dbe809766accbed0ac6"
project_key = ""
chain_account_addr = ""
chain_encryption = "sm2"


gas_coefficient = 1.5
gas = 400000
amount = 200000
account_gas = 4000000
denom = "uirita"


[redis]
address = "127.0.0.1:6379"
db = 0
password = ""

[ddc]
ddc_authority_address = "0xBcE9AA1924D7197C9C945e43638Bf589f91bcB71"
ddc_charge_address = "0xF41b6185bFB22E2EFC5fB8395Fa3B952951E2d0b"
ddc_721_address = "0x74b6114d011891Ac21FD1d586bc7F3407c63c216"
ddc_1155_address = "0x9f7388e114DfDFAbAF8e4b881894E4C7e1b52C17"
ddc_gateway_url = "http://192.168.150.42:8545"

chain_id = "dev"
grpc_address = "192.168.150.42:9090"
rpc_address = "tcp://192.168.150.42:26657"
project_id = "a36dc219dbdd4dbe809766accbed0ac6"
project_key = ""
chain_account_addr = ""
ddc_encryption = "eth_secp256k1"

gas_coefficient = 1.5
gas = 400000
amount = 200000
account_gas = 4000000
denom  = "uirita"

[bsn]
#门户OpenAPI URL
bsn_url = "http://117.107.141.162:18080"
#创建账户接口地址
api_address="/ddcoai/sys/v1/opb/account/create/save"
#门户OpenAPI Token
api_token = "eyJ0eXAiOiJKV1QiLCJ0eXBlIjoiT1BFTi1BUEktSldUIiwiYWxnIjoiSFMyNTYifQ.eyJsb2dpbk5hbWUiOiJCaWFuamllQUkyMDIyIiwiZXhwIjo0ODA0MTk1MzY2fQ.knlVH7QxQV5Q-T3zXUf4P22mX0bJZlXQ7inkA8E-8ms"
#用户类型(1=平台方 2=平台方的用户)
opb_chain_client_type= 2
#开放联盟链框架ID（调用接口：开放联盟链-框架列表查询）
opb_chain_id= 2
#链账户类型（调用接口：开放联盟链-框架支持的链账户类型）
opb_key_type= 3
#是否接入官方DDC合约 1=不接入 5=接入
open_ddc= 5
#DDC业务开通凭证 内容需要通过json转义
proof="{\"claim\":{\"entName\":\"上海边界智能科技有限公司\",\"domain\":\"https://wenchang.bianjie.ai\",\"loginName\":\"BianjieAI2022\",\"did\":\"did:bsn:ryJ1DZexzEr2ouLtLhXoNju3NKw\"},\"context\":\"https://www.w3.org/2018/credentials/v1\",\"cptId\":\"512201102044218347\",\"created\":\"2022-03-22 06:57:26\",\"expirationDate\":\"2042-03-22\",\"id\":\"1506163121985818624\",\"issuerDid\":\"did:bsn:34XUcjabSjGdwJMF686FUz6oBDXn\",\"proof\":{\"creator\":\"did:bsn:34XUcjabSjGdwJMF686FUz6oBDXn\",\"type\":\"Secp256k1\",\"signatureValue\":\"MQyB2exd/NcXerzAHwLViUw60BEN+O468VbJIh6gKgUJSik5B1lRtANP+a2/XOoWocLakSbWenl0sOLkxXP2BAE=\"},\"type\":\"Proof\",\"userDid\":\"did:bsn:ryJ1DZexzEr2ouLtLhXoNju3NKw\"}"