[app]
env = "dev"
log_level = "debug"
log_format = "text"
addr = ":8080"
prometheus_addr = "0.0.0.0:9092"
signature_auth = false
timestamp_auth = false
router_prefix = "v2"
grpc_timeout = 1000000
http_timeout = 1000000

[mysql]
host = "192.168.150.40"
port = 23306
username = "root"
password = "rootPassword"
db = "core"
max_open_conns = 100
max_idle_conns = 20
#单位为小时
max_life_time = 1

[redis]
host = "127.0.0.1:6379"
password = ""
db = 11

[grpc_client]
#iritaopb_native = "192.168.150.42:20000"
iritaopb_native = "localhost:10000"
state_gateway = "192.168.150.44:10000"

[project]
secret_pwd = "Console_Projects_Secrets"

