[app]
env = "dev"
log_level = "debug"
log_format = "text"
addr = ":8080"
prometheus_addr = "0.0.0.0:9092"
signature_auth = false
timestamp_auth = false
router_prefix = "v2"
grpc_timeout = 1000000
http_timeout = 1000000
limit = 200 # 数据查询条数上限

[mysql]
#host = "192.168.0.136"
#port = 3306
#username = "root"
#password = "rootPassword"
host = "192.168.0.136"
port = 3306
username = "root"
password = "rootPassword"
db = "core"
max_open_conns = 100
max_idle_conns = 20
#单位为小时
max_life_time = 1

[redis]
host = "127.0.0.1:6379"
password = ""
db = 11

[grpc_client]
tianzhou_evm = "192.168.0.157:11000"
state_gateway = "192.168.150.44:10000"
wallet_server = "192.168.150.40:11000"
irita_layer2 = ":10000"

[project]
secret_pwd = "Console_Projects_Secrets"

