[app]
name = "open-api"
version = "v0.4.0"
env = "dev"
log_level = "debug"
log_format = "text"
addr = ":8096"
prometheus_addr = "0.0.0.0:9092"
signature_auth = false
timestamp_auth = false
router_prefix = "v1beta1"
grpc_timeout = 1

[mysql]
host = "192.168.150.40"
port = 23306
username = "root"
password = "rootPassword"
# host = "192.168.150.40"
# port = 23306
db = "core"
# username = "core"
# password = "corePassword"
max_open_conns = 100
max_idle_conns = 20
#单位为小时
max_life_time = 1

[redis]
host = "127.0.0.1:6379"
password = ""
db = 11

[grpc_client]
wenchangchain_ddc_addr = "192.168.150.41:10000"
wenchangchain_native_addr = ":10000"
irita_opb_native_addr = "192.168.150.43:10000"
state_gateway_addr = "192.168.150.44:10000"


[project]
secret_pwd = "Console_Projects_Secrets"

