[app]
env = "dev"
log_level = "debug"
log_format = "text"
addr = ":8090"
prometheus_addr = "0.0.0.0:9093"
signature_auth = false
timestamp_auth = false
router_prefix = "v2"
grpc_timeout = 1000000
http_timeout = 1000000
limit = 200 # 数据查询条数上限

[mysql]
host = "192.168.0.136"
port = 3306
username = "root"
password = "rootPassword"
db = "core"
max_open_conns = 100
max_idle_conns = 20
#单位为小时
max_life_time = 1

[redis]
host = "192.168.150.40:6379"
password = "redisPassword"
db = 11

[grpc_client]
tianzhou_evm = "192.168.0.157:11000"
state_gateway = "192.168.150.44:10000"
wallet_server = "192.168.150.40:11000"
irita_layer2 = "192.168.150.45:10000"
sign_server = "192.168.150.45:10001"
tianzhou_native = "192.168.150.43:10000"

[project]
secret_pwd = "Console_Projects_Secrets"


